LIB_DIR = ../../ime_build
INCLUDE = -I../../include -I../../include/csinn -I../../include/shl_public -I../utils -I./layer
CFLAGS = -O0 -g3 -static
CFLAGS += -march=rv64gcv_zfh_zvfh -mabi=lp64d
CFLAGS += -ffunction-sections -fdata-sections -Wl,--gc-sections
CFLAGS += -DCSINN_API=19
CFLAGS += -DSHL_BUILD_IME -DBASIC_DEBUG
LIB_NAME = shl
CC = /home/artyom/spacemit-toolchain-linux-glibc-x86_64-v1.1.2/bin/riscv64-unknown-linux-gnu-gcc
CPLUS = /home/artyom/spacemit-toolchain-linux-glibc-x86_64-v1.1.2/bin/riscv64-unknown-linux-gnu-g++
TYPE=8832

test_objs =

test_objs += fullyconnected.o

utils_objs =
utils_objs += ../utils/test_utils.o

all: csi

csi: $(utils_objs) $(test_objs)

$(utils_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(test_objs): %.o: %.cpp
	$(CPLUS) -c $(CFLAGS) $(INCLUDE) -D DTYPE=$(TYPE) $< -o $@
	$(CPLUS) $@  $(CFLAGS) $(BOARD) $(utils_objs) -L$(LIB_DIR) -l$(LIB_NAME) -lc -lm -o $@.elf -lgcov

clean:
	rm -rf  $(test_objs) $(utils_objs) *.a *.asm *.elf *.asm
